package com.example.ibatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.auto_id
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    private Integer autoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.age
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.money
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.reg_time
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.auto_id
     *
     * @return the value of person.auto_id
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public Integer getAutoId() {
        return autoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.auto_id
     *
     * @param autoId the value for person.auto_id
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public void setAutoId(Integer autoId) {
        this.autoId = autoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.age
     *
     * @return the value of person.age
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.age
     *
     * @param age the value for person.age
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.money
     *
     * @return the value of person.money
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.money
     *
     * @param money the value for person.money
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.reg_time
     *
     * @return the value of person.reg_time
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.reg_time
     *
     * @param regTime the value for person.reg_time
     *
     * @mbggenerated Mon Jun 27 16:35:32 CST 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}