package com.example.ibatis.dao;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.example.ibatis.model.Person;
import com.example.pojo.QueryCondition;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Mon Jun 27 14:19:56 CST 2016
     */
    int deleteByPrimaryKey(Integer autoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Mon Jun 27 14:19:56 CST 2016
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Mon Jun 27 14:19:56 CST 2016
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Mon Jun 27 14:19:56 CST 2016
     */
    Person selectByPrimaryKey(Integer autoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Mon Jun 27 14:19:56 CST 2016
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Mon Jun 27 14:19:56 CST 2016
     */
    int updateByPrimaryKey(Person record);
    
    int updateMoney(Map<String, Object> params);
    
    BigDecimal selectMoney(Integer autoId);
    
    Integer queryPersonListCount(QueryCondition condition);
    
    List<Person> queryPersonList(QueryCondition condition);
    
    int insertExist(Person record);
}